### PR TITLE
added geolocation button and display of coordinates

### PR DESCRIPTION
**Pull request by catburston**

### CODE REVIEW

**Comment by iamricard** [comment]
Since this is a development-only feature (because we'll later put it on the main files), I'd like a folder just for it, like `geo/`

/cc @xsimov @catburston @SirArslaan

**Comment by naoisegolden** [comment]
@catburston client wants to see how it is looking so far in a Nexus 4… can you add a screen capture here please? :trollface: 

[hint](https://developer.chrome.com/devtools/docs/mobile-emulation)

**Comment by iamricard** [comment]
@naoisegolden 

Button only
screen shot 2014-08-03 at 16 01 24

Button and coords
screen shot 2014-08-03 at 16 01 03

**Comment by naoisegolden** [comment]
:+1: looking good. Thanks!

**Pull request merged**
